# Generated by Django 3.1.4 on 2022-01-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probleme',
            name='priorite',
            field=models.CharField(choices=[('-1', 'Inconnu'), ('0', 'Normal'), ('1', 'Urgent'), ('2', 'Critique')], default='Inconnu', max_length=50),
        ),
    ]
