# Generated by Django 3.1.4 on 2022-01-24 17:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_api', '0002_auto_20220124_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='date_echeance',
        ),
        migrations.AddField(
            model_name='ticket',
            name='date_echeancee',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 24, 17, 46, 9, 529479, tzinfo=utc), null=True),
        ),
    ]
