# Generated by Django 3.1.4 on 2022-01-24 17:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_api', '0003_auto_20220124_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='date_echeancee',
        ),
        migrations.AddField(
            model_name='ticket',
            name='date_echeance',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 24, 17, 47, 23, 67841, tzinfo=utc), null=True),
        ),
    ]
